#!/usr/bin/env python
# -*- coding: ASCII -*-

"""
:Author: Job van Schipstal
:Contact: jgc.vanschipstal@gmail.com
:Date: 03-12-2023
TODO write explain
"""
# Import dependencies
import sys
from argparse import ArgumentParser

import numpy as np
import matplotlib.pyplot as plt

parser = ArgumentParser(description=__doc__)
parser.add_argument("-i", "--input",
                    help="Input statistic files as generated by "
                         "report_ancestral_coverage.py, one or more",
                    type=str, required=True, nargs="+")
parser.add_argument("-o", "--output",
                    help="File to write figure to, should be of a type "
                         "supported by matplotlib.pyplot",
                    type=str, required=True)
args = parser.parse_args()

COLORS = ["#003459", "#007ea7"]

COLUMN_MAP = [["high_align", "Unmasked"],
              ["low_align", "Masked"]]


def load_table(file: str) -> dict:
    """
    Loads configuration from tsv table file.
    The double commented (##) line is read as column names

    :param file: str, filename to load configuration from
    :return: dict key is entry label and value is dict,
    with key column label and the value of that column
    """
    file_h = open(file, "r")
    elements = []
    chrom_dict = {}
    for line in file_h:
        line = line.strip()
        parts = line.split("\t")
        if line.startswith("##") or len(line) == 0:
            continue
        if line.startswith("#"):
            elements = parts[1:]
            continue
        current_fields = chrom_dict.get(parts[0], {})
        current_fields.update(dict([(label, value) for label, value
                                    in zip(elements, parts[1:])]))
        chrom_dict[parts[0]] = current_fields
    file_h.close()
    return chrom_dict


def plot_dict(data_dict: dict, columns: list, axis, factor=1,
              labels=False, summary=False, width=0.9) -> None:
    bottom = np.zeros(len(data_dict))
    for i, col in enumerate(columns):
        values = []
        for counts in data_dict.values():
            values.append(float(counts[col[0]]) / factor)
        p = axis.bar(list(data_dict.keys()), values, width,
                     label=col[1], bottom=bottom, color=COLORS[i])
        bottom += values
        if labels:
            axis.bar_label(p, fmt="%.3g", label_type='center', color="#fafafa")

    if summary:
        y_offset = None
        for key, counters in data_dict.items():
            total = 0.0
            for col in columns:
                total += float(counters[col[0]]) / factor
            if not y_offset:
                y_offset = total / 100
            axis.text(key, total + y_offset, f"{total:.3g}", ha='center',
                      weight='bold')
    axis.legend()


if __name__ == '__main__':
    # Output type 1: all chr and total compared
    if len(args.input) == 1:
        sys.stderr.write(f"Single sample, writing per chr output...\n")
        sample = load_table(args.input[0])
        fig, (ax1, ax2) = plt.subplots(nrows=2, figsize=(15, 10))
        chrom_only = sample.copy()
        chrom_only.pop("Total")
        plot_dict(chrom_only, COLUMN_MAP,
                  ax1, factor=1000000, labels=True, summary=True)
        ax1.set_title("Aligning bases by chromosome, in million")
        plot_dict(sample,
                  [[col + "_frq", name] for col, name in COLUMN_MAP],
                  ax2, labels=True, summary=True)
        ax2.set_title("Fraction of aligning bases by chromosome")
        ax2.set_ylim((0, 1))
        plt.savefig(args.output)
        sys.exit(0)  # Done, Successful

    # Output type 2: individual chr compared between ancestors
    samples = {}
    for ancestor in args.input:
        samples[ancestor.split(".")[0]] = load_table(ancestor)
    first = next(iter(samples.values()))
    chroms = list(first.keys())
    rows = len(chroms)
    fig, axs = plt.subplots(nrows=rows, ncols=2, figsize=(20, rows * 6))
    for i, chrom in enumerate(chroms):
        chrom_data = {}
        for key, values in samples.items():
            # print(f"{key} - {values}")
            chrom_data[key] = values[chrom]
        plot_dict(chrom_data, COLUMN_MAP,
                  axs[i][0], factor=1000000, labels=True, summary=True)
        axs[i][0].set_title(f"Aligning bases for {chrom} by Ancestor,"
                            f" in millions")
        plot_dict(chrom_data,
                  [[col + "_frq", name] for col, name in COLUMN_MAP],
                  axs[i][1], labels=True, summary=True)
        axs[i][1].set_title(f"Fraction of aligning bases for {chrom} "
                            f"by Ancestor")
        axs[i][1].set_ylim((0, 1))
    plt.savefig(args.output)
    sys.exit(0)  # Done, Successful
